name: lenssim
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - notebook
  - ipykernel
  - numpy
  - scipy
  - pandas
  - matplotlib
  - astropy
  - lenstronomy
  - tqdm
  - h5py
  - healpy
  - lsstdesc-gcr-catalogs
